apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-first.fullname" . }}
  labels:
    {{- include "api-first.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "api-first.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "api-first.labels" . | nindent 8 }}
        {{- include "api-first.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "api-first.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.env.SERVER_PORT | default 8080 }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: DATABASE_HOST
              value: {{ .Values.database.host | quote }}
            - name: DATABASE_PORT
              value: {{ .Values.database.port | quote }}
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-first.fullname" . }}-db-creds
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-first.fullname" . }}-db-creds
                  key: password
            - name: DATABASE_NAME
              value: {{ .Values.database.name | quote }}
            - name: DATABASE_SSLMODE
              value: {{ .Values.database.sslmode | quote }}
            - name: DATABASE_MAX_CONNS
              value: {{ .Values.database.maxConns | quote }}
            - name: DATABASE_MIN_CONNS
              value: {{ .Values.database.minConns | quote }}
            - name: DATABASE_MAX_LIFETIME
              value: {{ .Values.database.maxLifetime | quote }}
            - name: REDIS_ADDR
              value: {{ .Values.redis.addr | quote }}
            - name: REDIS_DB
              value: {{ .Values.redis.db | quote }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}