apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-first.fullname" . }}-db-creds
  labels:
    {{- include "api-first.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.database.user | b64enc | quote }}
  password: {{ .Values.database.password | b64enc | quote }}